"""Install script generation for Corely workers."""

import base64
import hashlib
import os
import secrets
from typing import Optional

# Default encryption password
DEFAULT_PASSWORD = "cor4ly-p4ssword"


def encrypt_token(token: str, password: str = DEFAULT_PASSWORD) -> str:
    """
    Encrypt the worker token using AES-256-CBC via openssl-compatible format.

    Uses PBKDF2 key derivation with random salt for security.
    The output is base64 encoded and can be decrypted with:
    echo "<encrypted>" | base64 -d | openssl enc -aes-256-cbc -d -pbkdf2 -pass pass:<password>
    """
    import subprocess

    # Use openssl to encrypt (ensures compatibility with the install script)
    result = subprocess.run(
        [
            "openssl", "enc", "-aes-256-cbc", "-pbkdf2", "-salt",
            "-pass", f"pass:{password}",
            "-base64"
        ],
        input=token.encode(),
        capture_output=True,
    )

    if result.returncode != 0:
        raise RuntimeError(f"Encryption failed: {result.stderr.decode()}")

    return result.stdout.decode().strip()


def generate_install_script(
    server_url: str,
    worker_token: str,
    encryption_password: str = DEFAULT_PASSWORD,
    binary_base_url: Optional[str] = None,
) -> str:
    """
    Generate a bash install script that:
    1. Prompts for the decryption password
    2. Decrypts the worker token
    3. Detects OS and architecture
    4. Downloads and installs the worker binary
    5. Configures autostart with auto-update
    """

    # Encrypt the worker token
    encrypted_token = encrypt_token(worker_token, encryption_password)

    # Use server URL for binary downloads if not specified
    if binary_base_url is None:
        binary_base_url = server_url.rstrip("/")

    script = f'''#!/bin/bash
#
# Corely Worker Installer
# Generated by {server_url}
#
# Usage: curl -fsSL {server_url}/install.sh | bash
#

set -e

BLUE='\\033[0;34m'
GREEN='\\033[0;32m'
RED='\\033[0;31m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

echo -e "${{BLUE}}"
echo "   ____                _       "
echo "  / ___|___  _ __ ___ | |_   _ "
echo " | |   / _ \\| '__/ _ \\| | | | |"
echo " | |__| (_) | | |  __/| | |_| |"
echo "  \\____\\___/|_|  \\___||_|\\__, |"
echo "                        |___/ "
echo -e "${{NC}}"
echo "Corely Worker Installer"
echo "========================"
echo ""

# Encrypted worker token (AES-256-CBC with PBKDF2)
ENCRYPTED_TOKEN="{encrypted_token}"

# Server configuration
SERVER_URL="{server_url}"
BINARY_BASE_URL="{binary_base_url}"

# Prompt for decryption password (read from /dev/tty for curl|bash compatibility)
echo -n "Enter installation password: "
read -s PASSWORD < /dev/tty
echo ""

# Decrypt the worker token
echo -e "${{BLUE}}Decrypting configuration...${{NC}}"
WORKER_TOKEN=$(echo "$ENCRYPTED_TOKEN" | openssl enc -aes-256-cbc -d -pbkdf2 -pass "pass:$PASSWORD" -base64 2>/dev/null)

if [ -z "$WORKER_TOKEN" ]; then
    echo -e "${{RED}}Error: Invalid password or corrupted configuration${{NC}}"
    exit 1
fi

echo -e "${{GREEN}}Configuration decrypted successfully${{NC}}"
echo ""

# Detect OS and architecture
detect_platform() {{
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    case "$OS" in
        linux)
            OS="linux"
            ;;
        darwin)
            OS="macos"
            ;;
        mingw*|msys*|cygwin*)
            OS="windows"
            ;;
        *)
            echo -e "${{RED}}Unsupported operating system: $OS${{NC}}"
            exit 1
            ;;
    esac

    case "$ARCH" in
        x86_64|amd64)
            ARCH="x86_64"
            ;;
        aarch64|arm64)
            ARCH="aarch64"
            ;;
        armv7l)
            ARCH="armv7"
            ;;
        *)
            echo -e "${{RED}}Unsupported architecture: $ARCH${{NC}}"
            exit 1
            ;;
    esac

    echo "$OS-$ARCH"
}}

PLATFORM=$(detect_platform)
OS=$(echo $PLATFORM | cut -d'-' -f1)
echo -e "${{BLUE}}Detected platform: $PLATFORM${{NC}}"

# Install system dependencies on Linux
install_linux_deps() {{
    echo -e "${{BLUE}}Installing system dependencies...${{NC}}"

    if command -v apt-get &> /dev/null; then
        # Debian/Ubuntu
        sudo apt-get update -qq
        sudo apt-get install -y -qq libxdo3 libssl3 || true
    elif command -v dnf &> /dev/null; then
        # Fedora/RHEL
        sudo dnf install -y xdotool openssl || true
    elif command -v pacman &> /dev/null; then
        # Arch
        sudo pacman -S --noconfirm xdotool openssl || true
    elif command -v zypper &> /dev/null; then
        # OpenSUSE
        sudo zypper install -y xdotool libopenssl1_1 || true
    else
        echo -e "${{YELLOW}}Warning: Could not detect package manager. You may need to install libxdo manually.${{NC}}"
    fi
}}

# Install dependencies on Linux
if [ "$OS" = "linux" ]; then
    install_linux_deps
fi

# Determine installation mode: try root-level first, fall back to user
determine_install_mode() {{
    if [ "$(id -u)" = "0" ]; then
        # Running as root - use system-wide installation
        echo "system"
    elif sudo -n true 2>/dev/null; then
        # Have passwordless sudo - use system-wide
        echo "system"
    else
        # No root access - use user installation
        echo "user"
    fi
}}

INSTALL_MODE=$(determine_install_mode)
echo -e "${{BLUE}}Installation mode: $INSTALL_MODE${{NC}}"

# Set paths based on installation mode
if [ "$INSTALL_MODE" = "system" ]; then
    INSTALL_DIR="/opt/corely/bin"
    CONFIG_DIR="/etc/corely"
    LOG_DIR="/var/log/corely"
    RUN_AS_ROOT=true
else
    INSTALL_DIR="$HOME/.local/bin"
    CONFIG_DIR="$HOME/.config/corely"
    LOG_DIR="$HOME/.config/corely"
    RUN_AS_ROOT=false
fi

BINARY_NAME="corely-worker"
BINARY_PATH="$INSTALL_DIR/$BINARY_NAME"

# Create directories
echo -e "${{BLUE}}Creating directories...${{NC}}"
if [ "$RUN_AS_ROOT" = true ]; then
    sudo mkdir -p "$INSTALL_DIR"
    sudo mkdir -p "$CONFIG_DIR"
    sudo mkdir -p "$LOG_DIR"
else
    mkdir -p "$INSTALL_DIR"
    mkdir -p "$CONFIG_DIR"
fi

# Download the worker binary
BINARY_URL="$BINARY_BASE_URL/downloads/corely-worker-$PLATFORM"
echo -e "${{BLUE}}Downloading worker binary from $BINARY_URL...${{NC}}"

TEMP_BINARY=$(mktemp)
if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -fsSL -w "%{{http_code}}" -o "$TEMP_BINARY" "$BINARY_URL" 2>/dev/null || echo "000")
elif command -v wget &> /dev/null; then
    wget -q -O "$TEMP_BINARY" "$BINARY_URL" && HTTP_CODE="200" || HTTP_CODE="000"
else
    echo -e "${{RED}}Error: curl or wget is required${{NC}}"
    exit 1
fi

if [ "$HTTP_CODE" != "200" ]; then
    echo -e "${{RED}}Error: Could not download pre-built binary (HTTP $HTTP_CODE)${{NC}}"
    echo -e "${{YELLOW}}Please check your internet connection or try again later.${{NC}}"
    rm -f "$TEMP_BINARY"
    exit 1
fi

# Install binary
if [ "$RUN_AS_ROOT" = true ]; then
    sudo mv "$TEMP_BINARY" "$BINARY_PATH"
    sudo chmod +x "$BINARY_PATH"
else
    mv "$TEMP_BINARY" "$BINARY_PATH"
    chmod +x "$BINARY_PATH"
fi
echo -e "${{GREEN}}Binary downloaded successfully${{NC}}"

# Create configuration file
echo -e "${{BLUE}}Creating configuration...${{NC}}"
CONFIG_CONTENT="# Corely Worker Configuration
SERVER_URL=$SERVER_URL
WORKER_TOKEN=$WORKER_TOKEN
BINARY_BASE_URL=$BINARY_BASE_URL
PLATFORM=$PLATFORM"

if [ "$RUN_AS_ROOT" = true ]; then
    echo "$CONFIG_CONTENT" | sudo tee "$CONFIG_DIR/worker.conf" > /dev/null
    sudo chmod 600 "$CONFIG_DIR/worker.conf"
else
    echo "$CONFIG_CONTENT" > "$CONFIG_DIR/worker.conf"
    chmod 600 "$CONFIG_DIR/worker.conf"
fi

# Create wrapper script that loads config and handles auto-update
WRAPPER_SCRIPT='#!/bin/bash
# Corely worker wrapper with auto-update support

# Determine config location
if [ -f "/etc/corely/worker.conf" ]; then
    CONFIG_FILE="/etc/corely/worker.conf"
    INSTALL_DIR="/opt/corely/bin"
    LOG_DIR="/var/log/corely"
    IS_SYSTEM=true
elif [ -f "$HOME/.config/corely/worker.conf" ]; then
    CONFIG_FILE="$HOME/.config/corely/worker.conf"
    INSTALL_DIR="$HOME/.local/bin"
    LOG_DIR="$HOME/.config/corely"
    IS_SYSTEM=false
else
    echo "Configuration not found"
    exit 1
fi

source "$CONFIG_FILE"

# Auto-update function
check_for_updates() {{
    if [ -z "$BINARY_BASE_URL" ] || [ -z "$PLATFORM" ]; then
        return 0
    fi

    CURRENT_VERSION=$("$INSTALL_DIR/corely-worker" --version 2>/dev/null | head -1 || echo "unknown")
    VERSION_URL="$BINARY_BASE_URL/api/worker/version"

    LATEST_VERSION=$(curl -fsSL "$VERSION_URL" 2>/dev/null || echo "")

    if [ -n "$LATEST_VERSION" ] && [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
        echo "$(date): Update available: $CURRENT_VERSION -> $LATEST_VERSION" >> "$LOG_DIR/update.log"

        BINARY_URL="$BINARY_BASE_URL/downloads/corely-worker-$PLATFORM"
        TEMP_BINARY=$(mktemp)

        if curl -fsSL -o "$TEMP_BINARY" "$BINARY_URL" 2>/dev/null; then
            chmod +x "$TEMP_BINARY"
            if [ "$IS_SYSTEM" = true ]; then
                sudo mv "$TEMP_BINARY" "$INSTALL_DIR/corely-worker"
            else
                mv "$TEMP_BINARY" "$INSTALL_DIR/corely-worker"
            fi
            echo "$(date): Updated to $LATEST_VERSION" >> "$LOG_DIR/update.log"
        else
            rm -f "$TEMP_BINARY"
        fi
    fi
}}

# Check for updates on startup (in background)
check_for_updates &

# Run the worker
exec "$INSTALL_DIR/corely-worker" --server "$SERVER_URL/ws/worker" --token "$WORKER_TOKEN" "$@"
'

if [ "$RUN_AS_ROOT" = true ]; then
    echo "$WRAPPER_SCRIPT" | sudo tee "$INSTALL_DIR/corely" > /dev/null
    sudo chmod +x "$INSTALL_DIR/corely"
else
    echo "$WRAPPER_SCRIPT" > "$INSTALL_DIR/corely"
    chmod +x "$INSTALL_DIR/corely"
fi

# Add to PATH if needed (user mode only)
add_to_path() {{
    if [ "$RUN_AS_ROOT" = true ]; then
        # System install is in /opt/corely/bin, add to system PATH
        if [ ! -f /etc/profile.d/corely.sh ]; then
            echo 'export PATH="$PATH:/opt/corely/bin"' | sudo tee /etc/profile.d/corely.sh > /dev/null
        fi
        return
    fi

    SHELL_NAME=$(basename "$SHELL")
    case "$SHELL_NAME" in
        bash)
            RC_FILE="$HOME/.bashrc"
            ;;
        zsh)
            RC_FILE="$HOME/.zshrc"
            ;;
        *)
            RC_FILE=""
            ;;
    esac

    if [ -n "$RC_FILE" ] && [ -f "$RC_FILE" ]; then
        if ! grep -q "$INSTALL_DIR" "$RC_FILE" 2>/dev/null; then
            echo "" >> "$RC_FILE"
            echo "# Corely worker" >> "$RC_FILE"
            echo "export PATH=\\"\\$PATH:$INSTALL_DIR\\"" >> "$RC_FILE"
            echo -e "${{GREEN}}Added $INSTALL_DIR to PATH in $RC_FILE${{NC}}"
        fi
    fi
}}

add_to_path

# Setup autostart
setup_autostart() {{
    echo -e "${{BLUE}}Setting up autostart...${{NC}}"

    case "$(uname -s)" in
        Darwin)
            # macOS: Create LaunchAgent
            PLIST_DIR="$HOME/Library/LaunchAgents"
            PLIST_FILE="$PLIST_DIR/com.corely.worker.plist"
            mkdir -p "$PLIST_DIR"

            cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.corely.worker</string>
    <key>ProgramArguments</key>
    <array>
        <string>$INSTALL_DIR/corely</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$HOME/.config/corely/worker.log</string>
    <key>StandardErrorPath</key>
    <string>$HOME/.config/corely/worker.log</string>
</dict>
</plist>
EOF

            launchctl unload "$PLIST_FILE" 2>/dev/null || true
            launchctl load "$PLIST_FILE"
            echo -e "${{GREEN}}LaunchAgent installed and started${{NC}}"
            ;;

        Linux)
            if command -v systemctl &> /dev/null; then
                if [ "$RUN_AS_ROOT" = true ]; then
                    # System-level service
                    sudo tee /etc/systemd/system/corely-worker.service > /dev/null << EOF
[Unit]
Description=Corely Worker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/corely
Restart=always
RestartSec=10
Environment="HOME=/root"

[Install]
WantedBy=multi-user.target
EOF

                    sudo systemctl daemon-reload
                    sudo systemctl enable corely-worker
                    sudo systemctl start corely-worker
                    echo -e "${{GREEN}}Systemd system service installed and started${{NC}}"
                else
                    # User-level service
                    mkdir -p "$HOME/.config/systemd/user"

                    cat > "$HOME/.config/systemd/user/corely-worker.service" << EOF
[Unit]
Description=Corely Worker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/corely
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

                    systemctl --user daemon-reload
                    systemctl --user enable corely-worker
                    systemctl --user start corely-worker
                    echo -e "${{GREEN}}Systemd user service installed and started${{NC}}"
                fi
            else
                # Fallback to cron @reboot
                CRON_CMD="@reboot $INSTALL_DIR/corely >> $LOG_DIR/worker.log 2>&1"
                (crontab -l 2>/dev/null | grep -v "corely"; echo "$CRON_CMD") | crontab -
                echo -e "${{GREEN}}Cron job installed for autostart${{NC}}"

                # Start now
                nohup "$INSTALL_DIR/corely" >> "$LOG_DIR/worker.log" 2>&1 &
                echo -e "${{GREEN}}Worker started in background${{NC}}"
            fi
            ;;

        *)
            echo -e "${{YELLOW}}Autostart not configured for this OS${{NC}}"
            echo -e "${{YELLOW}}Please start manually: $INSTALL_DIR/corely${{NC}}"
            ;;
    esac
}}

# Request macOS permissions
request_macos_permissions() {{
    echo -e "${{BLUE}}Requesting macOS permissions...${{NC}}"
    echo "The worker needs the following permissions to function:"
    echo "  - Screen Recording (for screen capture)"
    echo "  - Accessibility (for input control)"
    echo ""
    echo "System permission dialogs will appear. Please grant access."
    echo ""

    # Trigger Screen Recording permission by attempting a screenshot
    echo -e "${{BLUE}}Requesting Screen Recording permission...${{NC}}"
    "$BINARY_PATH" --request-permissions 2>/dev/null &
    PERM_PID=$!
    sleep 3
    kill $PERM_PID 2>/dev/null || true

    echo ""
    echo -e "${{YELLOW}}If permission dialogs didn't appear, please manually grant access:${{NC}}"
    echo "  System Settings > Privacy & Security > Screen Recording"
    echo "  System Settings > Privacy & Security > Accessibility"
    echo ""
    echo -n "Press Enter once you've granted permissions... "
    read -r < /dev/tty
    echo ""
}}

# Ask about autostart
echo ""
echo -n "Do you want to set up autostart? [Y/n] "
read -r AUTOSTART_RESPONSE < /dev/tty

case "$AUTOSTART_RESPONSE" in
    [nN]*)
        echo -e "${{YELLOW}}Skipping autostart setup${{NC}}"
        ;;
    *)
        # Request permissions on macOS before starting
        if [ "$(uname -s)" = "Darwin" ]; then
            request_macos_permissions
        fi
        setup_autostart
        ;;
esac

echo ""
echo -e "${{GREEN}}========================================${{NC}}"
echo -e "${{GREEN}}Corely Worker installation complete!${{NC}}"
echo -e "${{GREEN}}========================================${{NC}}"
echo ""
echo "Installation directory: $INSTALL_DIR"
echo "Configuration: $CONFIG_DIR/worker.conf"
echo ""
echo "To start manually:"
echo "  $INSTALL_DIR/corely"
echo ""
echo "To check status (systemd):"
if [ "$RUN_AS_ROOT" = true ]; then
    echo "  sudo systemctl status corely-worker"
else
    echo "  systemctl --user status corely-worker"
fi
echo ""
echo "To view logs:"
echo "  tail -f $LOG_DIR/worker.log"
echo ""
'''

    return script
