"""Install script generation for Corely workers."""

import base64
import hashlib
import os
import secrets
from typing import Optional

# Default encryption password
DEFAULT_PASSWORD = "cor4ly-p4ssword"


def encrypt_token(token: str, password: str = DEFAULT_PASSWORD) -> str:
    """
    Encrypt the worker token using AES-256-CBC via openssl-compatible format.

    Uses PBKDF2 key derivation with random salt for security.
    The output is base64 encoded and can be decrypted with:
    echo "<encrypted>" | base64 -d | openssl enc -aes-256-cbc -d -pbkdf2 -pass pass:<password>
    """
    import subprocess

    # Use openssl to encrypt (ensures compatibility with the install script)
    result = subprocess.run(
        [
            "openssl", "enc", "-aes-256-cbc", "-pbkdf2", "-salt",
            "-pass", f"pass:{password}",
            "-base64"
        ],
        input=token.encode(),
        capture_output=True,
    )

    if result.returncode != 0:
        raise RuntimeError(f"Encryption failed: {result.stderr.decode()}")

    return result.stdout.decode().strip()


def generate_install_script(
    server_url: str,
    worker_token: str,
    encryption_password: str = DEFAULT_PASSWORD,
    binary_base_url: Optional[str] = None,
) -> str:
    """
    Generate a bash install script that:
    1. Prompts for the decryption password
    2. Decrypts the worker token
    3. Detects OS and architecture
    4. Downloads and installs the worker binary
    5. Configures autostart
    """

    # Encrypt the worker token
    encrypted_token = encrypt_token(worker_token, encryption_password)

    # Use server URL for binary downloads if not specified
    if binary_base_url is None:
        binary_base_url = server_url.rstrip("/")

    script = f'''#!/bin/bash
#
# Corely Worker Installer
# Generated by {server_url}
#
# Usage: curl -fsSL {server_url}/install.sh | bash
#

set -e

BLUE='\\033[0;34m'
GREEN='\\033[0;32m'
RED='\\033[0;31m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

echo -e "${{BLUE}}"
echo "   ____                _       "
echo "  / ___|___  _ __ ___ | |_   _ "
echo " | |   / _ \\| '__/ _ \\| | | | |"
echo " | |__| (_) | | |  __/| | |_| |"
echo "  \\____\\___/|_|  \\___||_|\\__, |"
echo "                        |___/ "
echo -e "${{NC}}"
echo "Corely Worker Installer"
echo "========================"
echo ""

# Encrypted worker token (AES-256-CBC with PBKDF2)
ENCRYPTED_TOKEN="{encrypted_token}"

# Server configuration
SERVER_URL="{server_url}"
BINARY_BASE_URL="{binary_base_url}"

# Prompt for decryption password (read from /dev/tty for curl|bash compatibility)
echo -n "Enter installation password: "
read -s PASSWORD < /dev/tty
echo ""

# Decrypt the worker token
echo -e "${{BLUE}}Decrypting configuration...${{NC}}"
WORKER_TOKEN=$(echo "$ENCRYPTED_TOKEN" | openssl enc -aes-256-cbc -d -pbkdf2 -pass "pass:$PASSWORD" -base64 2>/dev/null)

if [ -z "$WORKER_TOKEN" ]; then
    echo -e "${{RED}}Error: Invalid password or corrupted configuration${{NC}}"
    exit 1
fi

echo -e "${{GREEN}}Configuration decrypted successfully${{NC}}"
echo ""

# Detect OS and architecture
detect_platform() {{
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    case "$OS" in
        linux)
            OS="linux"
            ;;
        darwin)
            OS="macos"
            ;;
        mingw*|msys*|cygwin*)
            OS="windows"
            ;;
        *)
            echo -e "${{RED}}Unsupported operating system: $OS${{NC}}"
            exit 1
            ;;
    esac

    case "$ARCH" in
        x86_64|amd64)
            ARCH="x86_64"
            ;;
        aarch64|arm64)
            ARCH="aarch64"
            ;;
        armv7l)
            ARCH="armv7"
            ;;
        *)
            echo -e "${{RED}}Unsupported architecture: $ARCH${{NC}}"
            exit 1
            ;;
    esac

    echo "$OS-$ARCH"
}}

PLATFORM=$(detect_platform)
echo -e "${{BLUE}}Detected platform: $PLATFORM${{NC}}"

# Installation paths
if [ "$OS" = "windows" ]; then
    INSTALL_DIR="$APPDATA/Corely"
    BINARY_NAME="corely-worker.exe"
else
    INSTALL_DIR="$HOME/.local/bin"
    BINARY_NAME="corely-worker"
fi

CONFIG_DIR="$HOME/.config/corely"
BINARY_PATH="$INSTALL_DIR/$BINARY_NAME"

# Create directories
echo -e "${{BLUE}}Creating directories...${{NC}}"
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"

# Download the worker binary
BINARY_URL="$BINARY_BASE_URL/downloads/corely-worker-$PLATFORM"
echo -e "${{BLUE}}Downloading worker binary from $BINARY_URL...${{NC}}"

if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -fsSL -w "%{{http_code}}" -o "$BINARY_PATH.tmp" "$BINARY_URL" 2>/dev/null || echo "000")
elif command -v wget &> /dev/null; then
    wget -q -O "$BINARY_PATH.tmp" "$BINARY_URL" && HTTP_CODE="200" || HTTP_CODE="000"
else
    echo -e "${{RED}}Error: curl or wget is required${{NC}}"
    exit 1
fi

if [ "$HTTP_CODE" != "200" ]; then
    echo -e "${{YELLOW}}Warning: Could not download pre-built binary (HTTP $HTTP_CODE)${{NC}}"
    echo -e "${{YELLOW}}You may need to build from source or download manually${{NC}}"
    rm -f "$BINARY_PATH.tmp"

    # Create a placeholder script that shows instructions
    cat > "$BINARY_PATH" << 'PLACEHOLDER'
#!/bin/bash
echo "Corely worker binary not installed."
echo "Please download from: https://github.com/your-org/corely/releases"
exit 1
PLACEHOLDER
    chmod +x "$BINARY_PATH"
else
    mv "$BINARY_PATH.tmp" "$BINARY_PATH"
    chmod +x "$BINARY_PATH"
    echo -e "${{GREEN}}Binary downloaded successfully${{NC}}"
fi

# Create configuration file
echo -e "${{BLUE}}Creating configuration...${{NC}}"
cat > "$CONFIG_DIR/worker.conf" << EOF
# Corely Worker Configuration
SERVER_URL=$SERVER_URL
WORKER_TOKEN=$WORKER_TOKEN
EOF
chmod 600 "$CONFIG_DIR/worker.conf"

# Create wrapper script that loads config
cat > "$INSTALL_DIR/corely" << 'WRAPPER'
#!/bin/bash
CONFIG_FILE="$HOME/.config/corely/worker.conf"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    exec "$HOME/.local/bin/corely-worker" --server "$SERVER_URL/ws/worker" --token "$WORKER_TOKEN" "$@"
else
    echo "Configuration not found: $CONFIG_FILE"
    exit 1
fi
WRAPPER
chmod +x "$INSTALL_DIR/corely"

# Add to PATH if needed
add_to_path() {{
    SHELL_NAME=$(basename "$SHELL")
    case "$SHELL_NAME" in
        bash)
            RC_FILE="$HOME/.bashrc"
            ;;
        zsh)
            RC_FILE="$HOME/.zshrc"
            ;;
        *)
            RC_FILE=""
            ;;
    esac

    if [ -n "$RC_FILE" ] && [ -f "$RC_FILE" ]; then
        if ! grep -q "$INSTALL_DIR" "$RC_FILE" 2>/dev/null; then
            echo "" >> "$RC_FILE"
            echo "# Corely worker" >> "$RC_FILE"
            echo "export PATH=\\"\\$PATH:$INSTALL_DIR\\"" >> "$RC_FILE"
            echo -e "${{GREEN}}Added $INSTALL_DIR to PATH in $RC_FILE${{NC}}"
        fi
    fi
}}

add_to_path

# Setup autostart
setup_autostart() {{
    echo -e "${{BLUE}}Setting up autostart...${{NC}}"

    case "$(uname -s)" in
        Darwin)
            # macOS: Create LaunchAgent
            PLIST_DIR="$HOME/Library/LaunchAgents"
            PLIST_FILE="$PLIST_DIR/com.corely.worker.plist"
            mkdir -p "$PLIST_DIR"

            cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.corely.worker</string>
    <key>ProgramArguments</key>
    <array>
        <string>$INSTALL_DIR/corely</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$HOME/.config/corely/worker.log</string>
    <key>StandardErrorPath</key>
    <string>$HOME/.config/corely/worker.log</string>
</dict>
</plist>
EOF

            launchctl unload "$PLIST_FILE" 2>/dev/null || true
            launchctl load "$PLIST_FILE"
            echo -e "${{GREEN}}LaunchAgent installed and started${{NC}}"
            ;;

        Linux)
            # Linux: Try systemd user service, fall back to cron
            if command -v systemctl &> /dev/null && [ -d "$HOME/.config/systemd/user" ] || mkdir -p "$HOME/.config/systemd/user"; then
                SERVICE_FILE="$HOME/.config/systemd/user/corely-worker.service"

                cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Corely Worker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/corely
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

                systemctl --user daemon-reload
                systemctl --user enable corely-worker
                systemctl --user start corely-worker
                echo -e "${{GREEN}}Systemd user service installed and started${{NC}}"
            else
                # Fallback to cron @reboot
                CRON_CMD="@reboot $INSTALL_DIR/corely >> $CONFIG_DIR/worker.log 2>&1"
                (crontab -l 2>/dev/null | grep -v "corely"; echo "$CRON_CMD") | crontab -
                echo -e "${{GREEN}}Cron job installed for autostart${{NC}}"

                # Start now
                nohup "$INSTALL_DIR/corely" >> "$CONFIG_DIR/worker.log" 2>&1 &
                echo -e "${{GREEN}}Worker started in background${{NC}}"
            fi
            ;;

        *)
            echo -e "${{YELLOW}}Autostart not configured for this OS${{NC}}"
            echo -e "${{YELLOW}}Please start manually: $INSTALL_DIR/corely${{NC}}"
            ;;
    esac
}}

# Ask about autostart
echo ""
echo -n "Do you want to set up autostart? [Y/n] "
read -r AUTOSTART_RESPONSE < /dev/tty

case "$AUTOSTART_RESPONSE" in
    [nN]*)
        echo -e "${{YELLOW}}Skipping autostart setup${{NC}}"
        ;;
    *)
        setup_autostart
        ;;
esac

echo ""
echo -e "${{GREEN}}========================================${{NC}}"
echo -e "${{GREEN}}Corely Worker installation complete!${{NC}}"
echo -e "${{GREEN}}========================================${{NC}}"
echo ""
echo "Installation directory: $INSTALL_DIR"
echo "Configuration: $CONFIG_DIR/worker.conf"
echo ""
echo "To start manually:"
echo "  $INSTALL_DIR/corely"
echo ""
echo "To check status (systemd):"
echo "  systemctl --user status corely-worker"
echo ""
echo "To view logs:"
echo "  tail -f $CONFIG_DIR/worker.log"
echo ""
'''

    return script
